# Generated by Django 2.0.3 on 2018-03-23 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import puzzles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_meta', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('hunt_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['parent', '-is_meta', 'number', 'id'],
            },
            bases=(models.Model, puzzles.models.JSONMixin),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('hunt_url', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'ordering': ['number', 'id'],
            },
            bases=(models.Model, puzzles.models.JSONMixin),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.Round'),
        ),
    ]
