# Generated by Django 3.0.2 on 2020-01-15 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_auto_20200110_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='url',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='activity_tracker',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='channel_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='sheet_id',
            field=models.CharField(db_index=True, default=None, max_length=1000, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ChannelParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('last_active', models.DateTimeField(null=True)),
                ('is_member', models.BooleanField()),
                ('channel_puzzle', models.ForeignKey(db_column='channel_name', on_delete=django.db.models.deletion.CASCADE, to='puzzles.Puzzle', to_field='slug')),
            ],
        ),
        migrations.AddIndex(
            model_name='channelparticipation',
            index=models.Index(fields=['channel_puzzle', 'user_id'], name='puzzles_cha_channel_7678c7_idx'),
        ),
    ]
