# Generated by Django 3.0.2 on 2020-11-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_puzzle_round_hunt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='discord_categories',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discord_identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
