# Generated by Django 3.0.2 on 2020-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_auto_20201111_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='slack_channel_id',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
