# Generated by Django 3.0.2 on 2020-11-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_puzzle_slack_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
