# Generated by Django 3.2.16 on 2024-01-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0015_channelparticipation_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='hunt_id',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='round',
            name='hunt_id',
            field=models.IntegerField(default=2024),
        ),
    ]
