# Generated by Django 3.2.16 on 2024-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0016_auto_20240109_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="""CREATE INDEX puzzles_userprofile_subscriptions_search ON "puzzles_userprofile" USING GIN (to_tsvector('english', COALESCE("puzzles_userprofile"."subscriptions", '')));""",
            reverse_sql="""DROP INDEX puzzles_userprofile_subscriptions_search;""",
        ),
    ]
