"""
Django settings for herring project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import json
import os
import ssl

import environ
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(BASE_DIR), '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# Required, with no default, so that no deployment can run on a known key.
# (The key that used to be hardcoded here is public in git history.)
# Generate one with:
#   python -c 'import secrets; print(secrets.token_urlsafe(50))'
SECRET_KEY = env.get_value('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY is set but empty")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.get_value('DEBUG', default=False)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'puzzles',
    'dashboard',
)

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    # Serves static files (STATIC_ROOT) from the app itself; see STORAGES.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'herring.urls'

# Where to go after logging in without a ?next= (the default, /accounts/profile/, doesn't exist).
LOGIN_REDIRECT_URL = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'herring', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'herring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': env.db_url(
        default='postgres:///herringdb',
        engine='django.db.backends.postgresql')
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Suppress new Django warning about auto fields being created implicitly
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS-only hardening: redirect http to https, and send cookies only over
# https. On by default (deployments are behind https); set HTTPS=0 to run
# over plain http locally (Docker Compose does this).
HERRING_HTTPS = env.bool('HTTPS', default=True)
SECURE_SSL_REDIRECT = HERRING_HTTPS
SESSION_COOKIE_SECURE = HERRING_HTTPS
CSRF_COOKIE_SECURE = HERRING_HTTPS
# HSTS tells browsers to use https for this host for this long. Kept short by
# default, since it can't be revoked before it expires.
SECURE_HSTS_SECONDS = env.int('HSTS_SECONDS', default=86400) if HERRING_HTTPS else 0
# Deliberately not enabled: includeSubDomains would apply HSTS to every
# subdomain of whatever domain hosts Herring, and preload is effectively
# permanent. Silence the deploy-checklist warnings about them.
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']
# Deliberately not including subdomains or requesting HSTS preload: those
# would affect other sites under the same domain.
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']

# Allow all host headers
ALLOWED_HOSTS = ['*']

# Static asset configuration
STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_DIRS = []
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

REDIS_URL = env.get_value('REDIS_URL', default='redis://localhost:6379/0')

HERRING_ACTIVATE_GAPPS = env.bool('ACTIVATE_GAPPS', default=False)
HERRING_ACTIVATE_DISCORD = env.bool('ACTIVATE_DISCORD', default=False)
HERRING_ENABLE_STANDALONE_DISCORD = env.bool('ENABLE_STANDALONE_DISCORD', default=False)
HERRING_CREATE_DISCORD_VOICE_CHANNELS = env.bool('CREATE_DISCORD_VOICE_CHANNELS', default=False)

HERRING_DEBUG_DISCORD_VERBOSELY = env.bool('DEBUG_DISCORD_VERBOSELY', default=False)

# Celery queue
CELERY_BROKER_URL = env.get_value('BROKER_URL', default=REDIS_URL)
#CELERY_BROKER_USE_SSL = { 'ssl_cert_reqs': 'none' }  # allow self-signed SSL certs
# max_retries here controls Celery's initial attempts to contact Redis, and
# defaults to *infinity*. Using a slightly smaller number is useful, for
# example, in development environments if the developer doesn't want to run a
# whole Redis+Celery stack and is okay with integrations not working.
CELERY_BROKER_TRANSPORT_OPTIONS = dict(max_retries=3)
CELERY_REDBEAT_REDIS_URL = REDIS_URL #+ "?ssl_cert_reqs=none"  # allow self-signed certificates
#CELERY_REDBEAT_REDIS_USE_SSL = { 'ssl_cert_reqs': 'none' }  # allow self-signed SSL certs
CELERY_BEAT_SCHEDULER = 'redbeat.RedBeatScheduler'

# Results are only kept for tasks that ask for them (ignore_result=False) --
# currently just add_user_to_puzzle, whose result the web process waits for --
# and only briefly.
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_IGNORE_RESULT = True
CELERY_RESULT_EXPIRES = 600
if REDIS_URL.startswith('rediss:'):
    # Same as puzzles.redis_state.redis_client: Heroku's Redis uses self-signed certificates.
    CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}

CELERY_BEAT_SCHEDULE = {}

if HERRING_ACTIVATE_GAPPS:
    CELERY_BEAT_SCHEDULE['read-google-sheets-changes'] = {
        'task': 'puzzles.tasks.process_google_sheets_changes',
        'schedule': 15.0,
    }

if HERRING_ACTIVATE_DISCORD and not HERRING_ENABLE_STANDALONE_DISCORD:
    CELERY_BEAT_SCHEDULE['check-connection-to-messaging'] = {
        'task': 'puzzles.tasks.check_connection_to_messaging',
        'schedule': 60.0,
    }

# How often Discord connection status is reported to Redis (see puzzles.redis_state).
HERRING_DISCORD_STATUS_INTERVAL_SECONDS = 30

if HERRING_ACTIVATE_DISCORD:
    CELERY_BEAT_SCHEDULE['report-discord-status'] = {
        'task': 'puzzles.tasks.report_discord_status',
        'schedule': float(HERRING_DISCORD_STATUS_INTERVAL_SECONDS),
    }

# This indirectly affects the expiration time of the lock RedBeat sets in
# Redis to ensure that only one scheduler is running. It largely doesn't
# matter unless the worker process with the active RedBeat instance is
# forcefully killed, in which case having a max_loop_interval of 30 seconds
# means that it could be up to 6 minutes before another RedBeat claims the
# lock and starts scheduling tasks again.
# [gwillen 2021]: shorten this to make restarts less terrible.
CELERY_BEAT_MAX_LOOP_INTERVAL = 10

# For some reason instead of 5x the loop interval, this defaults to 5x the
#   DEFAULT loop interval, which is 25 minutes, which is unacceptably long.
REDBEAT_LOCK_TIMEOUT = 60

# Previously in puzzles/tasks.py
HERRING_STATUS_CHANNEL = env.get_value('STATUS_CHANNEL', default='_dev_puzzle_status')
# Herring's public base URL, for links built outside a web request (e.g. Discord
# channel topics, written by Celery workers). A trailing slash is optional.
HERRING_HOST = env.get_value('HOST', default='http://localhost:8000').rstrip('/')
HERRING_PUZZLE_ACTIVITY_LOG_URL = env.get_value('PUZZLE_ACTIVITY_LOG_URL', default=None)
HERRING_PUZZLE_SITE_SESSION_COOKIE = env.get_value('PUZZLE_SITE_SESSION_COOKIE', default=None)

HERRING_DISCORD_GUILD_ID = int(env.get_value('DISCORD_GUILD', default=0))
HERRING_DISCORD_PROTECTED_CATEGORIES = set(json.loads(env.get_value('DISCORD_PROTECTED_CATEGORIES', default='[]')))
HERRING_DISCORD_PUZZLE_ANNOUNCEMENTS = env.get_value('DISCORD_ANNOUNCEMENTS', default='puzzle-announcements')
HERRING_DISCORD_BITRATE = env.int('DISCORD_BITRATE', default=128000)

# Previously in herring/secrets.py
HERRING_SECRETS = json.loads(env.get_value('SECRETS', default='{}'))
HERRING_FUCK_OAUTH = json.loads(env.get_value('FUCK_OAUTH', default='{}'))

# This should be more dynamic in the future.
HERRING_HUNT_ID = int(env.get_value('HUNT_ID', default=0))
HERRING_TEAM_NAME = env.get_value('TEAM_NAME', default="Non-Abelian Rage Theory")

HERRING_SOLVERTOOLS_URL = env.get_value('SOLVERTOOLS_URL', default="http://ireproof.org/")

# Log capture for the admin dashboard's log viewer (see herring/log_buffer.py):
# every process writes its records to a capped Redis stream. Which loggers are
# captured at what level is set at runtime from the dashboard.
HERRING_LOG_STREAM_KEY = 'herring:logs'
HERRING_LOG_LEVELS_KEY = 'herring:log-levels'
HERRING_LOG_BUFFER_ENTRIES = env.int('LOG_BUFFER_ENTRIES', default=20000)

# https://docs.djangoproject.com/en/5.2/topics/logging/
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            # The console stays at LOG_LEVEL even when the dashboard turns on DEBUG capture.
            'level': env.get_value('LOG_LEVEL', default='INFO'),
        },
        'buffer': {
            'class': 'herring.log_buffer.RedisLogHandler',
            'redis_url': REDIS_URL,
            'stream_key': HERRING_LOG_STREAM_KEY,
            'levels_key': HERRING_LOG_LEVELS_KEY,
            'max_entries': HERRING_LOG_BUFFER_ENTRIES,
        },
    },
    'root': {
        'handlers': ['console', 'buffer'],
        # Until a process reads the dashboard's level settings (at its first log record).
        'level': 'INFO',
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console', 'buffer'],
            'level': env.get_value(
                'DJANGO_DB_LOG_LEVEL',
                default='DEBUG' if DEBUG else 'INFO'),
            'propagate': False,
        },
    },
    'formatters': {
        'default': {
            # See https://hg.python.org/cpython/file/5c4ca109af1c/Lib/logging/__init__.py#l399
            'format': "[%(asctime)s %(levelname)-8s %(name)-15s] %(message)s",
            'dateformat': '%Y-%m-%d %H:%M:%S',
        },
    },
}
